// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// shift_left_simple
IntegerVector shift_left_simple(IntegerVector state);
RcppExport SEXP _cayleyR_shift_left_simple(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(shift_left_simple(state));
    return rcpp_result_gen;
END_RCPP
}
// shift_right_simple
IntegerVector shift_right_simple(IntegerVector state);
RcppExport SEXP _cayleyR_shift_right_simple(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(shift_right_simple(state));
    return rcpp_result_gen;
END_RCPP
}
// reverse_prefix_simple
IntegerVector reverse_prefix_simple(IntegerVector state, int k);
RcppExport SEXP _cayleyR_reverse_prefix_simple(SEXP stateSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(reverse_prefix_simple(state, k));
    return rcpp_result_gen;
END_RCPP
}
// shift_left
List shift_left(IntegerVector state, Nullable<List> coords);
RcppExport SEXP _cayleyR_shift_left(SEXP stateSEXP, SEXP coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type coords(coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(shift_left(state, coords));
    return rcpp_result_gen;
END_RCPP
}
// shift_right
List shift_right(IntegerVector state, Nullable<List> coords);
RcppExport SEXP _cayleyR_shift_right(SEXP stateSEXP, SEXP coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type coords(coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(shift_right(state, coords));
    return rcpp_result_gen;
END_RCPP
}
// reverse_prefix
List reverse_prefix(IntegerVector state, int k, Nullable<List> coords);
RcppExport SEXP _cayleyR_reverse_prefix(SEXP stateSEXP, SEXP kSEXP, SEXP coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type coords(coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(reverse_prefix(state, k, coords));
    return rcpp_result_gen;
END_RCPP
}
// apply_operations
List apply_operations(IntegerVector state, CharacterVector operations, int k, Nullable<List> coords);
RcppExport SEXP _cayleyR_apply_operations(SEXP stateSEXP, SEXP operationsSEXP, SEXP kSEXP, SEXP coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type operations(operationsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type coords(coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_operations(state, operations, k, coords));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cayleyR_shift_left_simple", (DL_FUNC) &_cayleyR_shift_left_simple, 1},
    {"_cayleyR_shift_right_simple", (DL_FUNC) &_cayleyR_shift_right_simple, 1},
    {"_cayleyR_reverse_prefix_simple", (DL_FUNC) &_cayleyR_reverse_prefix_simple, 2},
    {"_cayleyR_shift_left", (DL_FUNC) &_cayleyR_shift_left, 2},
    {"_cayleyR_shift_right", (DL_FUNC) &_cayleyR_shift_right, 2},
    {"_cayleyR_reverse_prefix", (DL_FUNC) &_cayleyR_reverse_prefix, 3},
    {"_cayleyR_apply_operations", (DL_FUNC) &_cayleyR_apply_operations, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_cayleyR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
