# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

shift_left_simple <- function(state) {
    .Call(`_cayleyR_shift_left_simple`, state)
}

shift_right_simple <- function(state) {
    .Call(`_cayleyR_shift_right_simple`, state)
}

reverse_prefix_simple <- function(state, k) {
    .Call(`_cayleyR_reverse_prefix_simple`, state, k)
}

shift_left <- function(state, coords = NULL) {
    .Call(`_cayleyR_shift_left`, state, coords)
}

shift_right <- function(state, coords = NULL) {
    .Call(`_cayleyR_shift_right`, state, coords)
}

reverse_prefix <- function(state, k, coords = NULL) {
    .Call(`_cayleyR_reverse_prefix`, state, k, coords)
}

apply_operations <- function(state, operations, k, coords = NULL) {
    .Call(`_cayleyR_apply_operations`, state, operations, k, coords)
}

