# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

shift_left_simple <- function(state) {
    .Call(`_cayleyR_shift_left_simple`, state)
}

shift_right_simple <- function(state) {
    .Call(`_cayleyR_shift_right_simple`, state)
}

reverse_prefix_simple <- function(state, k) {
    .Call(`_cayleyR_reverse_prefix_simple`, state, k)
}

shift_left <- function(state, coords = NULL) {
    .Call(`_cayleyR_shift_left`, state, coords)
}

shift_right <- function(state, coords = NULL) {
    .Call(`_cayleyR_shift_right`, state, coords)
}

reverse_prefix <- function(state, k, coords = NULL) {
    .Call(`_cayleyR_reverse_prefix`, state, k, coords)
}

get_reachable_states_light_cpp <- function(start_state, allowed_positions, k) {
    .Call(`_cayleyR_get_reachable_states_light_cpp`, start_state, allowed_positions, k)
}

find_best_random_combinations_cpp <- function(start_state, k, moves, combo_length, n_samples) {
    .Call(`_cayleyR_find_best_random_combinations_cpp`, start_state, k, moves, combo_length, n_samples)
}

openmp_threads <- function() {
    .Call(`_cayleyR_openmp_threads`)
}

apply_operations <- function(state, operations, k, coords = NULL) {
    .Call(`_cayleyR_apply_operations`, state, operations, k, coords)
}

short_path_bfs_cpp <- function(start_state, path, k, n_hits) {
    .Call(`_cayleyR_short_path_bfs_cpp`, start_state, path, k, n_hits)
}

sparse_bfs_cpp <- function(start_state, k, n_hubs = 7L, n_random = 3L, max_levels = 1000L) {
    .Call(`_cayleyR_sparse_bfs_cpp`, start_state, k, n_hubs, n_random, max_levels)
}

